title: "EPA Team"
description: "Experimental Plasma Accelerators (EPA) – research group at Instituto Superior Técnico (IST) working on plasma accelerators, laser–plasma interaction, and student thesis projects."
url: "https://nelsonmclopes.github.io"
baseurl: "/EPA_team_26"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
nav_enabled: true
permalink: pretty
